# run with `docker-compose up`
services:
  litecoin-core:
    image: uphold/litecoin-core:0.18.1@sha256:fb3148b0ca9fb3075ea7670c1690d4fa8bcf323d72a4c7192d8da235d95ee994
    command:
      -printtoconsole
      -regtest=1
