version: "3"
services:
  litecoin-core:
    build: .
    env_file: .env
    command:
      -printtoconsole
      -regtest=1
  trivy:
    image: aquasec/trivy:latest
    env_file: .env
    command:
      image -f json uphold/litecoin-core:0.18.1