apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: litecoin-core
  name: litecoin-core
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: litecoin-core
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: litecoin-core
    spec:
      containers:
        - args:
            - -printtoconsole
            - -regtest=1
          image: litecoin-core
          name: litecoin-core
          resources: {}
      restartPolicy: Always
status: {}
