apiVersion: v1
kind: PersistentVolume
metadata:
  name: litecoin-core
  labels:
    type: local
spec:
  capacity:
    storage: 5Gi
  hostPath:
    path: "/mnt/data/"
  accessModes:
    - ReadWriteOnce  
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: litecoin-core
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: litecoin-core
spec:
  selector:
    matchLabels:
      litecoin-core: v0.18.1
  replicas: 1
  template:
    metadata:
      labels:
        litecoin-core: v0.18.1        
    spec:
      containers:
      - name: litecoin-core
        image: uphold/litecoin-core:0.18.1
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        args:
          - -printtoconsole
          - -regtest=1
        volumeMounts:
          - name: data
            mountPath: "/mnt/data/"
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: trivyclaim        