apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: trivy
  name: trivy
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: trivy
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: trivy
    spec:
      containers:
        - args:
            - image
            - uphold/litecoin-core
          image: aquasec/trivy:latest
          name: trivy
          resources: {}
      restartPolicy: Always
status: {}
